package com.ciatech.uniconnect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TbAddressesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbAddressesAllPropertiesEquals(TbAddresses expected, TbAddresses actual) {
        assertTbAddressesAutoGeneratedPropertiesEquals(expected, actual);
        assertTbAddressesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbAddressesAllUpdatablePropertiesEquals(TbAddresses expected, TbAddresses actual) {
        assertTbAddressesUpdatableFieldsEquals(expected, actual);
        assertTbAddressesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbAddressesAutoGeneratedPropertiesEquals(TbAddresses expected, TbAddresses actual) {
        assertThat(expected)
            .as("Verify TbAddresses auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbAddressesUpdatableFieldsEquals(TbAddresses expected, TbAddresses actual) {
        assertThat(expected)
            .as("Verify TbAddresses relevant properties")
            .satisfies(e -> assertThat(e.getFullAddress()).as("check fullAddress").isEqualTo(actual.getFullAddress()))
            .satisfies(e ->
                assertThat(e.getCodeSectionCommunale()).as("check codeSectionCommunale").isEqualTo(actual.getCodeSectionCommunale())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbAddressesUpdatableRelationshipsEquals(TbAddresses expected, TbAddresses actual) {
        // empty method
    }
}
