package com.ciatech.uniconnect.domain;

import static com.ciatech.uniconnect.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TbLoginAttemptsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbLoginAttemptsAllPropertiesEquals(TbLoginAttempts expected, TbLoginAttempts actual) {
        assertTbLoginAttemptsAutoGeneratedPropertiesEquals(expected, actual);
        assertTbLoginAttemptsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbLoginAttemptsAllUpdatablePropertiesEquals(TbLoginAttempts expected, TbLoginAttempts actual) {
        assertTbLoginAttemptsUpdatableFieldsEquals(expected, actual);
        assertTbLoginAttemptsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbLoginAttemptsAutoGeneratedPropertiesEquals(TbLoginAttempts expected, TbLoginAttempts actual) {
        assertThat(expected)
            .as("Verify TbLoginAttempts auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbLoginAttemptsUpdatableFieldsEquals(TbLoginAttempts expected, TbLoginAttempts actual) {
        assertThat(expected)
            .as("Verify TbLoginAttempts relevant properties")
            .satisfies(e -> assertThat(e.getIpAddress()).as("check ipAddress").isEqualTo(actual.getIpAddress()))
            .satisfies(e -> assertThat(e.getUserAgent()).as("check userAgent").isEqualTo(actual.getUserAgent()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e ->
                assertThat(e.getAttemptAt())
                    .as("check attemptAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getAttemptAt())
            )
            .satisfies(e -> assertThat(e.getDeviceType()).as("check deviceType").isEqualTo(actual.getDeviceType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbLoginAttemptsUpdatableRelationshipsEquals(TbLoginAttempts expected, TbLoginAttempts actual) {
        assertThat(expected)
            .as("Verify TbLoginAttempts relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }
}
