package com.ciatech.uniconnect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TbOtpAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbOtpAllPropertiesEquals(TbOtp expected, TbOtp actual) {
        assertTbOtpAutoGeneratedPropertiesEquals(expected, actual);
        assertTbOtpAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbOtpAllUpdatablePropertiesEquals(TbOtp expected, TbOtp actual) {
        assertTbOtpUpdatableFieldsEquals(expected, actual);
        assertTbOtpUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbOtpAutoGeneratedPropertiesEquals(TbOtp expected, TbOtp actual) {
        assertThat(expected)
            .as("Verify TbOtp auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbOtpUpdatableFieldsEquals(TbOtp expected, TbOtp actual) {
        assertThat(expected)
            .as("Verify TbOtp relevant properties")
            .satisfies(e -> assertThat(e.getOtpCode()).as("check otpCode").isEqualTo(actual.getOtpCode()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getExpirationTime()).as("check expirationTime").isEqualTo(actual.getExpirationTime()))
            .satisfies(e -> assertThat(e.getAttemptCount()).as("check attemptCount").isEqualTo(actual.getAttemptCount()))
            .satisfies(e -> assertThat(e.getMaxAttempts()).as("check maxAttempts").isEqualTo(actual.getMaxAttempts()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbOtpUpdatableRelationshipsEquals(TbOtp expected, TbOtp actual) {
        assertThat(expected)
            .as("Verify TbOtp relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }
}
