package com.ciatech.uniconnect.domain;

import static com.ciatech.uniconnect.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TbPasswordHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPasswordHistoryAllPropertiesEquals(TbPasswordHistory expected, TbPasswordHistory actual) {
        assertTbPasswordHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertTbPasswordHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPasswordHistoryAllUpdatablePropertiesEquals(TbPasswordHistory expected, TbPasswordHistory actual) {
        assertTbPasswordHistoryUpdatableFieldsEquals(expected, actual);
        assertTbPasswordHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPasswordHistoryAutoGeneratedPropertiesEquals(TbPasswordHistory expected, TbPasswordHistory actual) {
        assertThat(expected)
            .as("Verify TbPasswordHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPasswordHistoryUpdatableFieldsEquals(TbPasswordHistory expected, TbPasswordHistory actual) {
        assertThat(expected)
            .as("Verify TbPasswordHistory relevant properties")
            .satisfies(e -> assertThat(e.getPasswordHash()).as("check passwordHash").isEqualTo(actual.getPasswordHash()))
            .satisfies(e -> assertThat(e.getPasswordSalt()).as("check passwordSalt").isEqualTo(actual.getPasswordSalt()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e -> assertThat(e.getIsCurrent()).as("check isCurrent").isEqualTo(actual.getIsCurrent()))
            .satisfies(e -> assertThat(e.getChangeReason()).as("check changeReason").isEqualTo(actual.getChangeReason()))
            .satisfies(e ->
                assertThat(e.getValidTo()).as("check validTo").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getValidTo())
            )
            .satisfies(e -> assertThat(e.getCanReuse()).as("check canReuse").isEqualTo(actual.getCanReuse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPasswordHistoryUpdatableRelationshipsEquals(TbPasswordHistory expected, TbPasswordHistory actual) {
        assertThat(expected)
            .as("Verify TbPasswordHistory relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }
}
