package com.ciatech.uniconnect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TbPermissionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPermissionsAllPropertiesEquals(TbPermissions expected, TbPermissions actual) {
        assertTbPermissionsAutoGeneratedPropertiesEquals(expected, actual);
        assertTbPermissionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPermissionsAllUpdatablePropertiesEquals(TbPermissions expected, TbPermissions actual) {
        assertTbPermissionsUpdatableFieldsEquals(expected, actual);
        assertTbPermissionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPermissionsAutoGeneratedPropertiesEquals(TbPermissions expected, TbPermissions actual) {
        assertThat(expected)
            .as("Verify TbPermissions auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPermissionsUpdatableFieldsEquals(TbPermissions expected, TbPermissions actual) {
        assertThat(expected)
            .as("Verify TbPermissions relevant properties")
            .satisfies(e -> assertThat(e.getAction()).as("check action").isEqualTo(actual.getAction()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbPermissionsUpdatableRelationshipsEquals(TbPermissions expected, TbPermissions actual) {
        assertThat(expected)
            .as("Verify TbPermissions relationships")
            .satisfies(e -> assertThat(e.getRoles()).as("check roles").isEqualTo(actual.getRoles()));
    }
}
