package com.ciatech.uniconnect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TbRolesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbRolesAllPropertiesEquals(TbRoles expected, TbRoles actual) {
        assertTbRolesAutoGeneratedPropertiesEquals(expected, actual);
        assertTbRolesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbRolesAllUpdatablePropertiesEquals(TbRoles expected, TbRoles actual) {
        assertTbRolesUpdatableFieldsEquals(expected, actual);
        assertTbRolesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbRolesAutoGeneratedPropertiesEquals(TbRoles expected, TbRoles actual) {
        assertThat(expected)
            .as("Verify TbRoles auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbRolesUpdatableFieldsEquals(TbRoles expected, TbRoles actual) {
        assertThat(expected)
            .as("Verify TbRoles relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getIsSystemRole()).as("check isSystemRole").isEqualTo(actual.getIsSystemRole()))
            .satisfies(e -> assertThat(e.getIsEditable()).as("check isEditable").isEqualTo(actual.getIsEditable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbRolesUpdatableRelationshipsEquals(TbRoles expected, TbRoles actual) {
        assertThat(expected)
            .as("Verify TbRoles relationships")
            .satisfies(e -> assertThat(e.getPermissions()).as("check permissions").isEqualTo(actual.getPermissions()))
            .satisfies(e -> assertThat(e.getUsers()).as("check users").isEqualTo(actual.getUsers()));
    }
}
