package com.ciatech.uniconnect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TbUsersAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbUsersAllPropertiesEquals(TbUsers expected, TbUsers actual) {
        assertTbUsersAutoGeneratedPropertiesEquals(expected, actual);
        assertTbUsersAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbUsersAllUpdatablePropertiesEquals(TbUsers expected, TbUsers actual) {
        assertTbUsersUpdatableFieldsEquals(expected, actual);
        assertTbUsersUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbUsersAutoGeneratedPropertiesEquals(TbUsers expected, TbUsers actual) {
        assertThat(expected)
            .as("Verify TbUsers auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbUsersUpdatableFieldsEquals(TbUsers expected, TbUsers actual) {
        assertThat(expected)
            .as("Verify TbUsers relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getOtherTelephone()).as("check otherTelephone").isEqualTo(actual.getOtherTelephone()))
            .satisfies(e -> assertThat(e.getDob()).as("check dob").isEqualTo(actual.getDob()))
            .satisfies(e -> assertThat(e.getNif()).as("check nif").isEqualTo(actual.getNif()))
            .satisfies(e -> assertThat(e.getCin()).as("check cin").isEqualTo(actual.getCin()))
            .satisfies(e -> assertThat(e.getNinu()).as("check ninu").isEqualTo(actual.getNinu()))
            .satisfies(e -> assertThat(e.getPassportNumber()).as("check passportNumber").isEqualTo(actual.getPassportNumber()))
            .satisfies(e -> assertThat(e.getLicenceNumber()).as("check licenceNumber").isEqualTo(actual.getLicenceNumber()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getSex()).as("check sex").isEqualTo(actual.getSex()))
            .satisfies(e -> assertThat(e.getMaritalStatus()).as("check maritalStatus").isEqualTo(actual.getMaritalStatus()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()))
            .satisfies(e -> assertThat(e.getTwoFactorEnabled()).as("check twoFactorEnabled").isEqualTo(actual.getTwoFactorEnabled()))
            .satisfies(e ->
                assertThat(e.getFailedLoginAttempts()).as("check failedLoginAttempts").isEqualTo(actual.getFailedLoginAttempts())
            )
            .satisfies(e -> assertThat(e.getIsBlocked()).as("check isBlocked").isEqualTo(actual.getIsBlocked()))
            .satisfies(e -> assertThat(e.getUserType()).as("check userType").isEqualTo(actual.getUserType()))
            .satisfies(e -> assertThat(e.getPassword()).as("check password").isEqualTo(actual.getPassword()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTbUsersUpdatableRelationshipsEquals(TbUsers expected, TbUsers actual) {
        assertThat(expected)
            .as("Verify TbUsers relationships")
            .satisfies(e -> assertThat(e.getTbAddresses()).as("check tbAddresses").isEqualTo(actual.getTbAddresses()))
            .satisfies(e -> assertThat(e.getRoles()).as("check roles").isEqualTo(actual.getRoles()));
    }
}
